mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<course_id>[0-9]+)/$', views.details, name='detail'),
    # ex: /polls/5/vote/
    url(r'^(?P<course_id>[0-9]+)/vote/$', views.addStu, name='vote'),
    # ex: /polls/add/
    url(r'^add/$', views.add, name='add'),
    # ex: /polls/remove/5/
    url(r'^remove/$', views.delete, name='delete'),
    # ex: /polls/removeStudent/5/course/4/
    url(r'^removeStudent/$', views.deleteStudent, name='deleteStudent'),
    # ex: /polls/edit/5/
    url(r'^edit/(?P<course_id>[0-9]+)$', views.editCourse, name='edit'),
    # ex: /polls/updateCourse/4/
    url(r'^updateCourse/(?P<course_id>[0-9]+)$', views.updateCourse, name='updateCourse'),
    # ex: /polls/editStu/4
    url(r'^editStu/(?P<student_id>[0-9]+)$', views.editStudent, name='editStu'),
    # ex: /polls/updateStudent
    url(r'^updateStudent/(?P<student_id>[0-9]+)/$', views.updateStudent, name='updateStu')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=300)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Student(models.Model):
    learnSubj = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    family = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " " + self.family

polls/views.py
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Course, Student


# Create your views here.


def index(request):
    listOfCourses = Course.objects.order_by('name')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'listOfCourses': listOfCourses
    }
    return HttpResponse(template.render(context, request))


def details(request, course_id):
    try:
        currentCourse = Course.objects.get(pk=course_id)
        listOfStudents = currentCourse.student_set.all()
        mainTitle = "Student list of " + currentCourse.name
    except Course.DoesNotExist:
        raise Http404("Course Does not exist")
    return render(request, 'polls/details.html', {
        'studentsList': listOfStudents,
        'mainTitle': mainTitle,
        'myId': course_id,
        'desc': currentCourse.description})


def addStu(request, course_id):
    courseCurr = get_object_or_404(Course, pk=course_id)
    try:
        courseCurr.student_set.create(name=request.POST['name'],
                                      family=request.POST['family'])
    except (KeyError, Course.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': courseCurr,
            'error_message': "You don't select a choice!"
        })
    else:
        courseCurr.save()
        return HttpResponseRedirect(reverse('polls:detail', args=(courseCurr.id,)))


def add(request):
    courseNew = Course(name=request.POST['name'], description=request.POST['description'])
    courseNew.save()
    return HttpResponseRedirect(reverse('polls:index'))


def delete(request):
    Course.objects.filter(id=request.POST["id"]).delete()
    return HttpResponseRedirect(reverse('polls:index'))


def deleteStudent(request):
    Student.objects.filter(id=request.POST["student_id"]).delete()
    return HttpResponseRedirect(reverse('polls:detail', args=(request.POST["course_id"],)))


def editCourse(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'polls/editCourse.html', {'course': course})


def updateCourse(request, course_id):
    Course.objects.filter(id=course_id).update(name=request.POST['name'],
                                               description=request.POST['description'])
    return HttpResponseRedirect(reverse('polls:index'))


def editStudent(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    courses = Course.objects.all()
    return render(request, 'polls/editStu.html', {
        'student': student, 'courses': courses})


def updateStudent(request, student_id):
    course = get_object_or_404(Course, name=request.POST['course'])
    Student.objects.filter(id=student_id).update(name=request.POST['name'],
                                                 family=request.POST['family'],
                                                 learnSubj=course)
    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" />

<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-3.1.1.min.js' %}"></script>

<div class="row" style="margin-top: 25px;">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">Course description</div>
            <div class="panel-body">
                {{ desc }}
            </div>
        </div>

        <table class="table table-bordered table-hover table-condensed" style="text-align: center;">
            <thead>
                <tr style="background-color:#F5F5F5;">
                    <td colspan="5">
                        {{ mainTitle }} course
                    </td>
                </tr>
                <tr style="background-color:#F5F5F5;">
                    <td>№</td>
                    <td>name</td>
                    <td>second name</td>
                    <td colspan="2">options</td>
                </tr>
            </thead>
            <tbody>
            {% for student in studentsList %}
                <tr>
                    <td>
                        {{forloop.counter}}
                    </td>
                    <td>
                        {{ student.name }}
                    </td>
                    <td>
                        {{ student.family }}
                    </td>
                    <td style="padding-left:15px;">
                        <form action="{% url 'polls:deleteStudent' %}" style="height: 10px; margin-top: -6px;" method="post" >
                            {% csrf_token %}
                            <input type="hidden" name="course_id" value="{{ myId }}">
                            <input type="hidden" name="student_id" value="{{ student.id }}">
                            <button type="submit" class="btn btn-link" style="color:red;">delete</button>
                        </form>
                    </td>
                    <td>
                        <a style="color:green" href="{% url 'polls:editStu' student.id %}">edit</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>


<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-info">
          <div class="panel-heading">add new Student</div>
          <div class="panel-body">
              <form action="{% url 'polls:vote' myId %}" method="post">
                  {% csrf_token %}
                  <input type="text" class="form-control" id="nameStu" name="name" placeholder="name" required><br>
                  <input type="text" class="form-control" id="familyStu"
                         name="family" placeholder="family" required><br>
                  <input class="btn btn-default btn btn-success" type="submit" value="add student" />
              </form>
          </div>
        </div>
    </div>
</div>

polls/templates/polls/editCourse.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" />

<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-3.1.1.min.js' %}"></script>

<div class="row" style="margin-top: 50px;">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">edit course</div>
          <div class="panel-body">
                <form action="{% url 'polls:updateCourse' course.id %}" method="post">
                {% csrf_token %}
                    <label>Course name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ course.name }}" required><br>
                    <label>Course description</label>
                    <input type="text" class="form-control" id="description"
                                 name="description" value="{{ course.description }}" required><br>
                    <input class="btn btn-default btn btn-warning" type="submit" value="save changes">
                </form>
          </div>
        </div>
    </div>
</div>

polls/templates/polls/editStu.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" />
<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-3.1.1.min.js' %}"></script>

<div class="row" style="margin-top: 50px;">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">edit student</div>
          <div class="panel-body">
                <form action="{% url 'polls:updateStu' student.id  %}" method="post">
                {% csrf_token %}
                    <label>name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ student.name }}" required><br>
                    <label>second name</label>
                    <input type="text" class="form-control" id="family"
                                 name="family" value="{{ student.family }}" required><br>

                    <label>course</label><br>
                    <select name="course" class="form-control">
                    {% for course in courses %}
                        {% if course.name == student.learnSubj.name %}
                            <option selected="selected" value="{{ course.name }}">{{ course.name }}</option>
                        {% else %}
                            <option value="{{ course.name }}">{{ course.name }}</option>
                        {% endif %}
                    {% endfor %}
                    </select>
                    <br>
                    <input class="btn btn-default btn btn-warning" type="submit" value="save changes">
                </form>
          </div>
        </div>
    </div>
</div>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" />

<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-3.1.1.min.js' %}"></script>

{% if listOfCourses %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-bordered table-hover table-condensed" style="margin-top:50px;">
            <thead>
                <tr style="text-align:center;">
                    <td>№</td>
                    <td>course</td>
                    <td colspan="2">options</td>
                </tr>
            </thead>
            <tbody>
                {% for course in listOfCourses %}
                <tr style="text-align:center;">
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        <a href="{% url 'polls:detail' course.id %}">{{ course.name }}</a>
                    </td>
                    <td>
                        <form action="{% url 'polls:delete' %}" style="height: 10px; margin-top: -6px;" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ course.id }}">
                            <button type="submit" class="btn btn-link" style="color:red;">remove</button>
                        </form>
                    </td>
                    <td>
                        <a style="color:green;" href="{% url 'polls:edit' course.id %}">edit</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<div class="col-md-6 col-md-offset-3" style="text-align: center;">
    <H2>No courses are available.</H2>
    <hr>
</div>
{% endif %}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-info">
          <div class="panel-heading">add new course</div>
          <div class="panel-body">
              <form action="{% url 'polls:add' %}" method="post">
                  {% csrf_token %}
                  <input type="text" class="form-control" id="name" name="name" placeholder="course name" required><br>
                  <input type="text" class="form-control" id="description"
                         name="description" placeholder="course description" required><br>
                  <input class="btn btn-default btn btn-success" type="submit" value="add course">
              </form>
          </div>
        </div>
    </div>
</div>